FROM mcr.microsoft.com/playwright/python:v1.48.0-jammy

WORKDIR /app

COPY requirements.browser.txt ./
RUN pip install --no-cache-dir -r requirements.browser.txt

COPY browser/ ./browser/

CMD ["python", "-m", "browser.runner"]
